apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: laravel-app
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        root /var/www/public;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass laravel:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location ~ /\.ht {
            deny all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: copy-laravel-files
          image: hammad1472/laravel-app:latest
          command:
            - sh
            - -c
            - cp -r /var/www/. /app/
          volumeMounts:
            - name: laravel-files
              mountPath: /app
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: laravel-files
              mountPath: /var/www
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: laravel-files
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: laravel-app
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080